(defpackage #:ssz-helpers
  (:use #:cl))

(in-package #:ssz-helpers)

(defun %concat-bytes (chunks)
  (let* ((total (reduce #'+ chunks :key #'length :initial-value 0))
         (out (make-array total :element-type '(unsigned-byte 8))))
    (let ((pos 0))
      (dolist (chunk chunks out)
        (replace out chunk :start1 pos)
        (incf pos (length chunk))))))

(defun %slice-bytes (bytes start end)
  (let* ((len (- end start))
         (out (make-array len :element-type '(unsigned-byte 8))))
    (replace out bytes :start1 0 :start2 start :end2 end)
    out))

(defun %u32-to-bytes (value)
  (let ((arr (make-array 4 :element-type '(unsigned-byte 8))))
    (dotimes (i 4 arr)
      (setf (aref arr i) (ldb (byte 8 (* 8 i)) value)))))

(defun %u32-from-bytes (bytes start)
  (let ((acc 0))
    (dotimes (i 4 acc)
      (setf acc (+ acc (ash (aref bytes (+ start i)) (* 8 i)))))))

(defun %u64-to-32-bytes (value)
  (let ((arr (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0)))
    (dotimes (i 8 arr)
      (setf (aref arr i) (ldb (byte 8 (* 8 i)) value)))))

(defun %u8-to-32-bytes (value)
  (let ((arr (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0)))
    (setf (aref arr 0) value)
    arr))

(defun %zero-bytes (n)
  (make-array n :element-type '(unsigned-byte 8) :initial-element 0))

(defun %pad-to-32 (bytes)
  (let ((len (length bytes)))
    (cond ((> len 32)
           (error "chunk too large: ~a bytes" len))
          ((= len 32) bytes)
          (t
           (let ((out (%zero-bytes 32)))
             (replace out bytes :start1 0)
             out)))))

(defun %sha256 (bytes)
  (let* ((pkg (find-package :ironclad))
         (sym (and pkg (find-symbol "DIGEST-SEQUENCE" pkg))))
    (if (and sym (fboundp sym))
        (funcall (symbol-function sym) :sha256 bytes)
        (error "ironclad not available; load ironclad to compute SHA256"))))

(defun %hash-pair (left right)
  (let ((buf (make-array 64 :element-type '(unsigned-byte 8))))
    (replace buf left :start1 0)
    (replace buf right :start1 32)
    (%sha256 buf)))

(defun %next-pow-of-two (n)
  (let ((v (max 1 n)))
    (if (zerop (logand v (1- v)))
        v
        (let ((p 1))
          (loop while (< p v) do (setf p (* 2 p)))
          p))))

(defun %merkleize (chunks &optional limit)
  (let* ((len (length chunks))
         (limit-val (and limit (max 0 limit))))
    (when (and limit-val (< limit-val len))
      (error "merkleize limit too small: ~a < ~a" limit-val len))
    (let* ((effective (if limit-val limit-val len))
           (size (%next-pow-of-two effective))
           (pad-count (- size len))
           (layer (if (> pad-count 0)
                      (append chunks
                              (loop repeat pad-count collect (%zero-bytes 32)))
                      (copy-list chunks))))
      (when (= (length layer) 0)
        (setf layer (list (%zero-bytes 32))))
      (loop while (> (length layer) 1) do
        (let ((out nil))
          (loop for (a b) on layer by #'cddr do
            (push (%hash-pair a b) out))
          (setf layer (nreverse out))))
      (car layer))))

(defun %merkleize-progressive (chunks &optional (num-leaves 1))
  (cond ((null chunks) (%zero-bytes 32))
        (t
         (let* ((n (max 1 num-leaves))
                (head (subseq chunks 0 (min n (length chunks))))
                (tail (nthcdr n chunks))
                (left (%merkleize-progressive tail (* n 4)))
                (right (%merkleize head n)))
           (%hash-pair left right)))))

(defun %bytes-to-chunks (bytes)
  (let ((len (length bytes))
        (chunks nil))
    (loop for start from 0 below len by 32 do
      (let ((end (min len (+ start 32))))
        (push (%pad-to-32 (%slice-bytes bytes start end)) chunks)))
    (nreverse chunks)))

(defun %mix-in-length (root length)
  (let* ((len-bytes (%u64-to-32-bytes length))
         (buf (%concat-bytes (list root len-bytes))))
    (%sha256 buf)))

(defun %mix-in-selector (root selector)
  (let* ((sel-bytes (%u8-to-32-bytes selector))
         (buf (%concat-bytes (list root sel-bytes))))
    (%sha256 buf)))

(defun %mix-in-active-fields (root packed)
  (let ((chunk (%pad-to-32 packed)))
    (%hash-pair root chunk)))

(defun %pack-bits (bits bit-count)
  (let* ((byte-len (ceiling bit-count 8))
         (out (make-array byte-len :element-type '(unsigned-byte 8)
                          :initial-element 0)))
    (dotimes (i bit-count out)
      (when (nth i bits)
        (let* ((byte-idx (floor i 8))
               (bit-idx (mod i 8))
               (mask (ash 1 bit-idx)))
          (setf (aref out byte-idx)
                (logior (aref out byte-idx) mask)))))))

(defun %unpack-bitvector (bytes bit-count)
  (let* ((byte-len (ceiling bit-count 8))
         (len (length bytes)))
    (unless (= len byte-len)
      (error "bitvector byte length mismatch: expected ~a, got ~a" byte-len len))
    (let ((bits nil))
      (dotimes (i bit-count (nreverse bits))
        (let* ((byte-idx (floor i 8))
               (bit-idx (mod i 8))
               (b (aref bytes byte-idx))
               (setp (not (zerop (logand b (ash 1 bit-idx))))))
          (push setp bits))))))

(defun %validate-bitvector-tail (bytes bit-count)
  (let* ((byte-len (ceiling bit-count 8))
         (unused (mod (- (* byte-len 8) bit-count) 8)))
    (when (and (> unused 0) (> byte-len 0))
      (let* ((last (aref bytes (- byte-len 1)))
             (mask (1- (ash 1 (- 8 unused)))))
        (when (/= (logand last (lognot mask)) 0)
          (error "bitvector has non-zero unused bits"))))))

(defun %pack-bitlist (bits)
  (let* ((bit-count (length bits))
         (total-bits (+ bit-count 1))
         (byte-len (ceiling total-bits 8))
         (out (make-array byte-len :element-type '(unsigned-byte 8)
                          :initial-element 0)))
    (dotimes (i bit-count)
      (when (nth i bits)
        (let* ((byte-idx (floor i 8))
               (bit-idx (mod i 8))
               (mask (ash 1 bit-idx)))
          (setf (aref out byte-idx)
                (logior (aref out byte-idx) mask)))))
    (let* ((delim-idx bit-count)
           (byte-idx (floor delim-idx 8))
           (bit-idx (mod delim-idx 8))
           (mask (ash 1 bit-idx)))
      (setf (aref out byte-idx)
            (logior (aref out byte-idx) mask)))
    out))

(defun %unpack-bitlist (bytes max-bits)
  (let ((len (length bytes)))
    (when (= len 0)
      (error "bitlist must contain a delimiting bit"))
    (let ((highest -1))
      (loop for i from (1- len) downto 0 do
        (let ((b (aref bytes i)))
          (when (> b 0)
            (loop for bit from 7 downto 0 do
              (when (not (zerop (logand b (ash 1 bit))))
                (setf highest (+ (* i 8) bit))
                (return)))
            (when (>= highest 0)
              (return)))))
      (when (< highest 0)
        (error "bitlist missing delimiting bit"))
      (let ((bit-count highest))
        (when (> bit-count max-bits)
          (error "bitlist exceeds max bits: ~a > ~a" bit-count max-bits))
        (let ((bits nil))
          (dotimes (i bit-count (nreverse bits))
            (let* ((byte-idx (floor i 8))
                   (bit-idx (mod i 8))
                   (b (aref bytes byte-idx))
                   (setp (not (zerop (logand b (ash 1 bit-idx))))))
              (push setp bits))))))))

(defun %ceil-div (num den)
  (nth-value 0 (ceiling num den)))
